micronaut:
  application:
    name: serverstm
  server:
    port: 8080
    cors:
      enabled: true
      web:
        allowedOrigins:
          http://localhost:4200/
        allowedMethods:
          - POST
          - PUT
          - GET
    tomcat:
      allow-trace: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:abc123}
datasources:
  default:
    url: jdbc:postgresql://localhost:5433/stmsave
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '21052508'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages: "com.stm"
    properties:
      hibernate:
        hbm2ddl:
          auto: update
